#!/bin/bash

# preinstall.sh
# Marc Thielemann, 2019/09/15

# redirect all output to /dev/null
exec >/dev/null 2>&1

helperPlistPath="$3/Library/LaunchDaemons/com.ripeda.privileges.helper.plist"
menubarPlistPath="$3/Library/LaunchAgents/com.ripeda.privileges-menubar.plist"

/usr/bin/killall Privileges

# unload the launchd plist only if installing on the boot volume
if [[ "$3" = "/" ]]; then
	/bin/launchctl bootout system "$helperPlistPath"
fi

currentUser=$(/bin/ls -l /dev/console | /usr/bin/awk '{ print $3 }')
currentUserUID=$(/usr/bin/id -u "$currentUser")
/bin/launchctl asuser "$currentUserUID" /bin/launchctl unload -w "$menubarPlistPath"

/bin/rm -rf "$helperPlistPath" \
            "$3/Library/PrivilegedHelperTools/com.ripeda.privileges.helper" \
            "$3/Applications/Privileges.app" \
            "$3/Library/LaunchAgents/com.ripeda.privileges-watchdog.plist" \
            "$3/Library/LaunchAgents/com.ripeda.privileges-menubar.plist" \
            "$3/Library/Application Support/RIPEDA/RIPEDA Client/Uninstall-RIPEDA-Privileges-Client.pkg"

if [[ -z $(/bin/ls -A "$3/Library/Application Support/RIPEDA/RIPEDA Client") ]]; then
    /bin/rm -rf "$3/Library/Application Support/RIPEDA/RIPEDA Client"
fi

if [[ -z $(/bin/ls -A "$3/Library/Application Support/RIPEDA") ]]; then
    /bin/rm -rf "$3/Library/Application Support/RIPEDA"
fi

# Delete old package receipts for installer
recipt_base="$3/var/db/receipts/com.ripeda.privileges-client-installer"
recipt_plist="$recipt_base.plist"
recipt_bom="$recipt_base.bom"

if [[ -f "$recipt_plist" ]]; then
    /bin/rm -f "$recipt_plist"
fi

if [[ -f "$recipt_bom" ]]; then
    /bin/rm -f "$recipt_bom"
fi

exit 0