#!/bin/bash

# preinstall.sh
# Marc Thielemann, 2019/09/15

# redirect all output to /dev/null
exec >/dev/null 2>&1

helperPlistPath="$3/Library/LaunchDaemons/corp.sap.privileges.helper.plist"
watchdogPlistPath="$3/Library/LaunchAgents/com.ripeda.privileges-watchdog.auto-start.plist"

/usr/bin/killall Privileges

# unload the launchd plist only if installing on the boot volume
if [[ "$3" = "/" ]]; then
	/bin/launchctl bootout system "$helperPlistPath"
fi

# Unload the watchdog plist
/bin/launchctl unload "$watchdogPlistPath"

/bin/rm -rf "$helperPlistPath" \
            "$3/Library/PrivilegedHelperTools/corp.sap.privileges.helper" \
            "$3/Applications/Privileges.app" \
            "$3/Library/LaunchAgents/com.ripeda.privileges-watchdog.auto-start.plist" \
            "$3/Library/Application Support/RIPEDA/RIPEDA Client/Uninstall-RIPEDA-Privileges-Client.pkg"

exit 0