name: CI - Build Application

on:
  push:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  build:
    name: Build
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip3 install pyinstaller

      - name: Build Project
        run: ./Build-Project.tool

      - name: Upload Privileges (Release)
        uses: actions/upload-artifact@v2
        with:
          name: RIPEDA-Privileges-Release.pkg
          path: ./products/Package/RIPEDA-Privileges-Release.pkg

      - name: Upload Privileges (Debug)
        uses: actions/upload-artifact@v2
        with:
          name: RIPEDA-Privileges-Debug.pkg
          path: ./products/Package/RIPEDA-Privileges-Debug.pkg