name: CI - Build Application

on:
  push:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  build:
    name: Build
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip3 install pyinstaller

      - name: Build Project
        run: ./Build-Project.tool

      - name: Upload Privileges (Release)
        uses: actions/upload-artifact@v2
        with:
          name: Install-RIPEDA-Privileges-Client-Release.pkg
          path: ./products/Package/Install-RIPEDA-Privileges-Client-Release.pkg

      - name: Upload Privileges (Debug)
        uses: actions/upload-artifact@v2
        with:
          name: Install-RIPEDA-Privileges-Client-Debug.pkg
          path: ./products/Package/Install-RIPEDA-Privileges-Client-Debug.pkg

      - name: Upload Privileges (Uninstaller)
        uses: actions/upload-artifact@v2
        with:
          name: Uninstall-RIPEDA-Privileges-Client.pkg
          path: ./products/Package/Uninstall-RIPEDA-Privileges-Client.pkg


      - name: Upload Privileges (Release) (on release)
        if: github.event_name == 'release'
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./products/Package/Install-RIPEDA-Privileges-Client-Release.pkg
          tag: ${{ github.ref }}
          file_glob: true


      - name: Upload Privileges (Debug) (on release)
        if: github.event_name == 'release'
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./products/Package/Install-RIPEDA-Privileges-Client-Debug.pkg
          tag: ${{ github.ref }}
          file_glob: true

      - name: Upload Privileges (Uninstaller) (on release)
        if: github.event_name == 'release'
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./products/Package/Uninstall-RIPEDA-Privileges-Client.pkg
          tag: ${{ github.ref }}
          file_glob: true