name: CI - Build Application

on:
  push:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  build:
    name: Build
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3

      - name: Build Project
        run: ./Build-Project.tool

      - name: Upload Privileges.app (Release)
        uses: actions/upload-artifact@v2
        with:
          name: Privileges-RELEASE.app.zip
          path: ./products/Package/RIPEDA-Privileges-Release.pkg

      - name: Upload Privileges.app (Debug)
        uses: actions/upload-artifact@v2
        with:
          name: Privileges-DEBUG.app.zip
          path: ./products/Package/RIPEDA-Privileges-Debug.pkg