name: CI - Build Application

on:
  push:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  build:
    name: Build
    runs-on: macos-latest

    env:
      # Signing
      ORG_MAC_IDENTITY: ${{ secrets.ORG_MAC_IDENTITY }}
      # App Signing
      ORG_MAC_DEVELOPER_ID_APPLICATION_CERT_P12_BASE64: ${{ secrets.ORG_MAC_DEVELOPER_ID_APPLICATION_CERT_P12_BASE64 }}
      ORG_MAC_DEVELOPER_ID_APPLICATION_CERT_P12_PASSWORD: ${{ secrets.ORG_MAC_DEVELOPER_ID_APPLICATION_CERT_P12_PASSWORD }}
      # PKG Signing
      ORG_MAC_DEVELOPER_ID_INSTALLER_CERT_P12_BASE64: ${{ secrets.ORG_MAC_DEVELOPER_ID_INSTALLER_CERT_P12_BASE64 }}
      ORG_MAC_DEVELOPER_ID_INSTALLER_CERT_P12_PASSWORD: ${{ secrets.ORG_MAC_DEVELOPER_ID_INSTALLER_CERT_P12_PASSWORD }}
      # Notarization
      ORG_MAC_NOTARIZATION_TEAM_ID: ${{ secrets.ORG_MAC_NOTARIZATION_TEAM_ID }}
      ORG_MAC_NOTARIZATION_APPLE_ID: ${{ secrets.ORG_MAC_NOTARIZATION_APPLE_ID }}
      ORG_MAC_NOTARIZATION_PASSWORD: ${{ secrets.ORG_MAC_NOTARIZATION_PASSWORD }}


    steps:
      - uses: actions/checkout@v3

      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip3 install macos-pkg-builder

      - name: Import Application Distribution Certificate
        uses: dhinakg/import-codesign-certs@master
        with:
          p12-file-base64: ${{ secrets.ORG_MAC_DEVELOPER_ID_APPLICATION_CERT_P12_BASE64 }}
          p12-password: ${{ secrets.ORG_MAC_DEVELOPER_ID_APPLICATION_CERT_P12_PASSWORD }}

      - name: Import Mac Installer Certificate
        uses: dhinakg/import-codesign-certs@master
        with:
          p12-file-base64: ${{ secrets.ORG_MAC_DEVELOPER_ID_INSTALLER_CERT_P12_BASE64 }}
          p12-password: ${{ secrets.ORG_MAC_DEVELOPER_ID_INSTALLER_CERT_P12_PASSWORD }}

      - name: Build Project
        run: ./Build-Project.tool --app_signing_identity "${{ env.ORG_MAC_IDENTITY }}" --pkg_signing_identity "${{ env.ORG_MAC_IDENTITY }}" --notarize_team_id "${{ env.ORG_MAC_NOTARIZATION_TEAM_ID }}" --notarize_apple_id "${{ env.ORG_MAC_NOTARIZATION_APPLE_ID }}" --notarize_password "${{ env.ORG_MAC_NOTARIZATION_PASSWORD }}"

      - name: Upload Privileges (Release)
        uses: actions/upload-artifact@v2
        with:
          name: Install-RIPEDA-Privileges-Client-Release.pkg
          path: ./products/Package/Install-RIPEDA-Privileges-Client-Release.pkg

      - name: Upload Privileges (Debug)
        uses: actions/upload-artifact@v2
        with:
          name: Install-RIPEDA-Privileges-Client-Debug.pkg
          path: ./products/Package/Install-RIPEDA-Privileges-Client-Debug.pkg

      - name: Upload Privileges (Uninstaller)
        uses: actions/upload-artifact@v2
        with:
          name: Uninstall-RIPEDA-Privileges-Client.pkg
          path: ./products/Package/Uninstall-RIPEDA-Privileges-Client.pkg


      - name: Upload Privileges (Release) (on release)
        if: github.event_name == 'release'
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./products/Package/Install-RIPEDA-Privileges-Client-Release.pkg
          tag: ${{ github.ref }}
          file_glob: true


      - name: Upload Privileges (Debug) (on release)
        if: github.event_name == 'release'
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./products/Package/Install-RIPEDA-Privileges-Client-Debug.pkg
          tag: ${{ github.ref }}
          file_glob: true

      - name: Upload Privileges (Uninstaller) (on release)
        if: github.event_name == 'release'
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./products/Package/Uninstall-RIPEDA-Privileges-Client.pkg
          tag: ${{ github.ref }}
          file_glob: true

      - name: Upload sample .mobileconfig (on release)
        if: github.event_name == 'release'
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./Sample RIPEDA Profile/RIPEDA-Privileges-Configuration.mobileconfig
          tag: ${{ github.ref }}
          file_glob: true